language: node_js

dist: xenial

node_js:
    - "8"
    - "10"
    - "11"

cache: yarn

if: tag IS blank

script:
    - set -e
    - yarn run lint
    - yarn run prettier:check
    - yarn run rebuild
    - set +e
